config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :temp_animes
    resources :initials
    resources :movies
    resources :episodes
    resources :anime_masters
  end
  resources :episode_comments, :only => [:create,:show] 
  resources :anime_comments, :only => [:create,:show]
  resources :anime, :only => [:index, :show]
  resources :episode, :only => [:show]
  post 'fav_animes/add', to: 'fav_animes#add' 
  get 'search', to: 'search#show'
  root to: 'anime#index' 
end

app/models/anime_comment.rb
class AnimeComment < ActiveRecord::Base
  belongs_to :anime_master
  validate :add_error
  def add_error
    # commentが空のときにエラーメッセージを追加する
    if comment.blank?
      errors[:base] << "コメントが未入力です"
    end
  end
end

app/controllers/anime_comments_controller.rb
class AnimeCommentsController < ApplicationController
  before_action :set_anime_comment, only: [:show, :edit, :update, :destroy]

  # GET /anime_comments
  # GET /anime_comments.json
  def index
    @anime_comments = AnimeComment.all
  end

  # GET /anime_comments/1
  # GET /anime_comments/1.json
  def show
  end

  # GET /anime_comments/new
  def new
    @anime_comment = AnimeComment.new
  end

  # GET /anime_comments/1/edit
  def edit
  end

  # POST /anime_comments
  # POST /anime_comments.json
  def create
    @anime_comment = AnimeComment.new(anime_comment_params)

    respond_to do |format|
      if @anime_comment.save
        format.html { redirect_to @anime_comment, notice: '下記の内容でコメントを投稿しました' }
        format.json { render :show, status: :created, location: @anime_comment }
      else
        format.html { render :new }
        format.json { render json: @anime_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anime_comments/1
  # PATCH/PUT /anime_comments/1.json
  def update
    respond_to do |format|
      if @anime_comment.update(anime_comment_params)
        format.html { redirect_to @anime_comment, notice: 'Anime comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @anime_comment }
      else
        format.html { render :edit }
        format.json { render json: @anime_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anime_comments/1
  # DELETE /anime_comments/1.json
  def destroy
    @anime_comment.destroy
    respond_to do |format|
      format.html { redirect_to anime_comments_url, notice: 'Anime comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime_comment
      @anime_comment = AnimeComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anime_comment_params
      params.require(:anime_comment).permit(:name, :comment, :is_valid, :anime_master_id)
    end
end

app/helpers/anime_comments_helper.rb
module AnimeCommentsHelper
end

app/views/anime_comments/_form.html.erb
<%= stylesheet_link_tag "comment", :media => "all" %>
<% if @anime_comment.errors.any? %>
  <div id="error_explanation">
      <% @anime_comment.errors.full_messages.each do |message| %>
        <div class="alert fade in alert-success "><button type="button" class="close" data-dismiss="alert">×</button><%= message %></div>
      <% end %>
  </div>
<% end %>
<%= render partial: 'shared/comment_create', locals: { new_comment: @anime_comment} %>

app/views/anime_comments/edit.html.erb
<h1>Editing Anime Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @anime_comment %> |
<%= link_to 'Back', anime_comments_path %>

app/views/anime_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Anime Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th>Is valid</th>
      <th>Anime master</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @anime_comments.each do |anime_comment| %>
      <tr>
        <td><%= anime_comment.name %></td>
        <td><%= anime_comment.comment %></td>
        <td><%= anime_comment.is_valid %></td>
        <td><%= anime_comment.anime_master %></td>
        <td><%= link_to 'Show', anime_comment %></td>
        <td><%= link_to 'Edit', edit_anime_comment_path(anime_comment) %></td>
        <td><%= link_to 'Destroy', anime_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Anime comment', new_anime_comment_path %>

app/views/anime_comments/new.html.erb
<h1>New Anime Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', anime_comments_path %>

app/views/anime_comments/show.html.erb
<div style="padding-left:5%;padding-right:5%">
  <div class="row">
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
      <label for="anime_comment_name">名前</label>
    </div>
    <div class="col-lg-10 col-md-9 col-sm-9 col-xs-12">
      <%= @anime_comment.name %>
    </div>
  </div>
  <div class="row"> 
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
      <label for="anime_comment_comment">コメント</label>
    </div> 
    <div class="col-lg-10 col-md-9 col-sm-9 col-xs-12">
      <%= simple_format(@anime_comment.comment) %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12"></div> 
    <div class="col-lg-10 col-md-9 col-sm-9 col-xs-12">
      <%= link_to '戻る', anime_path(@anime_comment.anime_master_id) %>
    </div>

  </div>
</div>