config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :temp_animes
    resources :initials
    resources :movies
    resources :episodes
    resources :anime_masters
  end
  resources :episode_comments, :only => [:create,:show] 
  resources :anime_comments, :only => [:create,:show]
  resources :anime, :only => [:index, :show]
  resources :episode, :only => [:show]
  post 'fav_animes/add', to: 'fav_animes#add' 
  get 'search', to: 'search#show'
  root to: 'anime#index' 
end

app/models/initial.rb
class Initial < ActiveRecord::Base
end

app/controllers/admin/initials_controller.rb
class Admin::InitialsController < ApplicationController
  before_action :set_initial, only: [:show, :edit, :update, :destroy]

  # GET /initials
  # GET /initials.json
  def index
    @initials = Initial.all
  end

  # GET /initials/1
  # GET /initials/1.json
  def show
  end

  # GET /initials/new
  def new
    @initial = Initial.new
  end

  # GET /initials/1/edit
  def edit
  end

  # POST /initials
  # POST /initials.json
  def create
    @initial = Initial.new(initial_params)

    respond_to do |format|
      if @initial.save
        format.html { redirect_to [:admin,@initial], notice: 'Initial was successfully created.' }
        format.json { render :show, status: :created, location: @initial }
      else
        format.html { render :new }
        format.json { render json: @initial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /initials/1
  # PATCH/PUT /initials/1.json
  def update
    respond_to do |format|
      if @initial.update(initial_params)
        format.html { redirect_to [:admin,@initial], notice: 'Initial was successfully updated.' }
        format.json { render :show, status: :ok, location: @initial }
      else
        format.html { render :edit }
        format.json { render json: @initial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /initials/1
  # DELETE /initials/1.json
  def destroy
    @initial.destroy
    respond_to do |format|
      format.html { redirect_to admin_initials_url, notice: 'Initial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_initial
      @initial = Initial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def initial_params
      params.require(:initial).permit(:name,:initial_group_id)
    end
end

app/helpers/admin/initials_helper.rb
module Admin::InitialsHelper
end

app/views/admin/initials/_form.html.erb
<%= form_for([:admin,@initial]) do |f| %>
  <% if @initial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@initial.errors.count, "error") %> prohibited this initial from being saved:</h2>

      <ul>
      <% @initial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :initial_group_id %><br>
    <%= f.number_field :initial_group_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/initials/edit.html.erb
<h1>Editing Initial</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@initial] %> |
<%= link_to 'Back', admin_initials_path %>

app/views/admin/initials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Initials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>GroupId</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @initials.each do |initial| %>
      <tr>
        <td><%= initial.name %></td>
        <td><%= initial.initial_group_id %></td>
        <td><%= link_to 'Show', admin_initial_path(initial) %></td>
        <td><%= link_to 'Edit', edit_admin_initial_path(initial) %></td>
        <td><%= link_to 'Destroy', admin_initial_path(initial), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Initial', new_admin_initial_path %>

app/views/admin/initials/new.html.erb
<h1>New Initial</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_initials_path %>

app/views/admin/initials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @initial.name %>
</p>

<%= link_to 'Edit', edit_admin_initial_path(@initial) %> |
<%= link_to 'Back', admin_initials_path %>