config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :temp_animes
    resources :initials
    resources :movies
    resources :episodes
    resources :anime_masters
  end
  resources :episode_comments, :only => [:create,:show] 
  resources :anime_comments, :only => [:create,:show]
  resources :anime, :only => [:index, :show]
  resources :episode, :only => [:show]
  post 'fav_animes/add', to: 'fav_animes#add' 
  get 'search', to: 'search#show'
  root to: 'anime#index' 
end

app/controllers/anime_controller.rb
class AnimeController < ApplicationController
  def index
    @animes = AnimeMaster.where("state=1")
    # render layout: 'anime_top'
  end
  def show 
    @anime = AnimeMaster.find(params[:id])
    @episodes = Episode.where(anime_master_id: params[:id]).order(chapter: :desc)
    @new_comment = AnimeComment.new
    @new_comment.anime_master_id = params[:id]
    @anime_comments = AnimeComment.where(anime_master_id: params[:id]).order("updated_at desc")
  end
end

app/helpers/anime_helper.rb
module AnimeHelper
  def get_big_img(img)
    if(img!=nil)
      return img.gsub(/_SL160_/,"_SL600_")
    end
      return image_path("no_image.png");
  end
  def get_list_img(img)
    if(img!=nil)
      return img
    end
    return "/assets/no_image.png"
  end
  def get_wday(day_of_week)
    case day_of_week
      when 0 then
        return "日曜"
      when 1 then
        return "月曜"
      when 2 then
        return "火曜"
      when 3 then
        return "水曜"
      when 4 then
        return "木曜"
      when 5 then
        return "金曜"
      when 6 then
        return "土曜"
      else
        return ""
    end
  end
end

app/views/anime/index.html.erb
<% content_for :h1_tag do %>
  まにあにめ
<% end %>
<div class="container-fluid">
  <div class="row-fluid">
<% @animes.each do |anime| %>
    <div class="col-md-3 col-sm-4 col-xs-6 "style="">
      <a href="<%=anime_path(anime)%>">
        <div class="new-animes"><img class="img-responsive img-center" style="max-height:160px;"
          src="<%=get_list_img(anime.image_path)%>"/></div>
      </a>
    <div class="title"><%=anime.title%></div>
    </div>
<% end %>
  </div>
</div>

app/views/anime/show.html.erb
<% content_for :title do %>
  <%= @anime.title %> 無料動画 
<% end %>
<% content_for :h1_tag do %>
 <%= @anime.title %>
<% end %>
<% content_for :header do %>
  <%= stylesheet_link_tag "anime", :media => "all" %>
  <%= stylesheet_link_tag "comment", :media => "all" %>
<% end %>
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-lg-5 col-md-6 col-sm-6 col-xs-12">
      <p><img class="img-responsive img-center anime-img" src="<%= get_big_img(@anime.image_path)%>"></p>
    </div>
    <div>
      <button onclick="continue_view(<%= @anime.id %>);" value="継続視聴">継続視聴</button>
    </div>
    <div>  
      <strong><%= @anime.title %> ストーリー</strong><br />
      <%= @anime.discription %>
    </div>
  </div>
</div>
<div class="episodes">
  <% @episodes.each do |episode| %>
    <p>
    <a href="<%= episode_path(episode) %>"> 
      <%= episode.chapter %>話 <%= episode.title %>
    </a>
    </p>
  <% end %>
</div>
<hr>
<%= render partial: 'shared/comment', locals: { comments:@anime_comments, anime_title:@anime.title} %>
<hr>
<%= render partial: 'shared/comment_create', locals: { new_comment: @new_comment} %>