config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :temp_animes
    resources :initials
    resources :movies
    resources :episodes
    resources :anime_masters
  end
  resources :episode_comments, :only => [:create,:show] 
  resources :anime_comments, :only => [:create,:show]
  resources :anime, :only => [:index, :show]
  resources :episode, :only => [:show]
  post 'fav_animes/add', to: 'fav_animes#add' 
  get 'search', to: 'search#show'
  root to: 'anime#index' 
end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :anime_master
  has_many :movies,dependent: :destroy
end

app/controllers/admin/episodes_controller.rb
class Admin::EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.page(params[:page])

  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to admin_episode_url, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to admin_episode_url, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to admin_episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:title, :chapter, :anime_master_id)
    end
end

app/controllers/episode_controller.rb
class EpisodeController < ApplicationController
  def show
    @episode = Episode.find(params[:id])
    @new_comment = EpisodeComment.new
    @new_comment.episode_id = params[:id]
    @episode_comments = EpisodeComment.where(episode_id: params[:id]).order("updated_at desc")
  end
end

app/helpers/admin/episodes_helper.rb
module Admin::EpisodesHelper
end

app/helpers/episode_helper.rb
module EpisodeHelper
end

app/views/admin/episodes/_form.html.erb
<%= form_for([:admin,@episode]) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :chapter %><br>
    <%= f.number_field :chapter %>
  </div>
  <div class="field">
    <%= f.label :anime_master_id %><br>
    <%= f.number_field :anime_master_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form' %>

<%= link_to 'Show', admin:@episode %> |
<%= link_to 'Back', admin_episodes_path %>

app/views/admin/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Episodes</h1>

<%= link_to '新規作成', new_admin_anime_master_path %>
<div><%= page_entries_info @episodes %></div>
<div><%= paginate @episodes %> </div>
<% @episodes.each do |episode| %>
  <div class="col-md-12">
    <% unless episode.anime_master.nil? %>
      <div class="col-md-12">アニメタイトル：<%= episode.anime_master.title %></div>
    <% end %>
    <div class="col-md-2">第<%= episode.chapter %>話</div>
    <div class="col-md-10">タイトル：<%= episode.title %></div>

    <div class="col-md-4"></div>
    <div class="col-md-8"></div>
    <div class="col-md-2"><%= link_to 'Show', admin_episodes_path %></div>
    <div class="col-md-2"><%= link_to 'Edit', edit_admin_episode_path(episode) %></div>
    <div class="col-md-2"><%= link_to 'Destroy', admin_episode_path(episode), method: :delete, data: { confirm: 'Are you sure?' } %></div>
  </div>
<% end %>
<div style="clear:both"><%= paginate @episodes %> </div>
<%= link_to 'New Episode', new_admin_episode_path %>

app/views/admin/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_episodes_path %>

app/views/admin/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @episode.title %>
</p>

<p>
  <strong>Chapter:</strong>
  <%= @episode.chapter %>
</p>

<p>
  <strong>Anime:</strong>
  <%= @episode.anime_master_id %>
</p>

<%= link_to 'Edit', edit_admin_episode_path(@episode) %> |
<%= link_to 'Back', admin_episodes_path %>